CREATE DATABASE amdb;
CREATE USER amuser WITH ENCRYPTED PASSWORD 'ampass';
GRANT ALL PRIVILEGES ON DATABASE amdb TO amuser;

\connect amdb
ALTER SCHEMA public OWNER TO amuser;
GRANT ALL ON SCHEMA public TO amuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO amuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO amuser;
